#!/usr/bin/env bash
# Configure web-02 to be identical to web-01

# install Nginx
sudo apt install nginx -y

# Returns a page saying "Hello World" when queried at the root with a curl GET request
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# has a custom 404 page saying "Ceci n'est pas une page"
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# configure Nginx so that it listens on port 80 with a HTTP response that contains
#+ a custom header X-Served_By and the hostname of the running server
echo "add_header X-Served-By $HOSTNAME" | sudo tee  -a /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
