#!/usr/bin/env bash
# Installs and configures HAproxy on the lb-01 server

# update packages
sudo apt-get update -y

# add haproxy ppa
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4

# load balancer configurations
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 183696-web-01 34.232.71.152:80 check
    server 183696-web-02 54.237.83.13:80 check
"

# haproxy install
sudo apt-get install haproxy -y
sudo -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
