#!/usr/bin/env bash
# fixes a web server so nginx runs as nginx user and listens on all active IPs on port 8080
sed -i "li user ngin;" /etc/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx restart
